📦 Declare mas as a Swift Package
mas-cli/mas pull request #350
Opened 2021-04-27 04:16 UTC by chris-araman

- Removes dependence on `carthage` and `make`.
- Moves sources to `Sources` and `Tests` as is the default in new Swift packages.
  - If others would prefer these remain as they were, we can instead specify the paths explicitly in `Package.swift`.
- Declares Swift package dependencies in Xcode project and `Package.swift`.
- `swift build` and `swift test` succeed, though `mas version` is currently broken (see below).

To Do:
- [ ] Decide whether we want to remove the Xcode project and add `swift package generate-xcodeproj` to `script/bootstrap` instead. This would allow us to avoid maintain multiple ways of building `mas`, and keeping duplicate dependency lists.
- [ ] Decide if it's okay to link `MasKit` as a library into `mas` instead of deploying it as a framework. SPM does not yet support building frameworks, only libraries and executables.
- [ ] Decide if we want to keep our `Info.plist`. SPM does not have a supported way to process and inject these, though we could probably manage to write some `.linkerSettings(.unsafeFlags(...))` hackery that would get the job done. It looks like we only inject copyright and version strings. The `version` command currently uses the injected version string. We could inject that in a different way.

2021-04-28 02:43 UTC, phatblat approved these changes

2021-04-29 03:06 UTC, phatblat commented
> Sorry I typed all this up last night and forgot to submit.

Yay! I've been wanting to do this for so long, but have not gotten around to it.

## To generate-xcodeproj or not to generate-xcodeproj?

I like the idea of generating the `xcodeproj` in the bootstrap script. I imagine that we'll ignore the file so that we don't check it in accidentally?

## MasKit framework

The only real reason MasKit exists is because the Xcode macOS CLI target doesn't support unit tests, or any embedded resources for that matter. I've come across one macOS GUI app that interfaced with the app store but they rolled their own hacks to the private frameworks; I'm not aware of any apps using MasKit.framework. I know that there are CLI dependencies on mas such as Chef, Ansible and ad-hoc scripts.

I believe we can change this packaging format to a library with little to no impact. But, since the separate framework was only created to facilitate testing, perhaps we no longer need it. Can we have the tests interface with any `@testable` internal API even if they are in an executable?

## Info.plist

The only use of `Info.plist` is that the version command fetches the value from `CFBundleShortVersionString`. If we can find a new home for the current version number (somewhere that's easy to remember) then we can lose the `Info.plist` file.

2021-04-29 04:01 UTC, chris-araman commented
> `generate-xcodeproj`
No longer necessary. Xcode can open the `mas` directory. It's magic! 🪄✨

> MasKit framework
Cool. Yeah, the tests now run against the MasKit library.

> Info.plist
Great! They're gone.

I think I have everything working except for the `mas.pkg` build now. Working on that next. Feel free to accept and merge this when you're ready, or wait for `mas.pkg`. I can just submit that as a separate PR if need be.

2021-04-29 05:30 UTC, chris-araman commented
The `mas.pkg` build works now. I've verified that installing it works as well. This PR is now ready to go as soon as you've accepted it.

2021-04-29 06:01 UTC, chris-araman commented
> If we can find a new home for the current version number (somewhere that's easy to remember) then we can lose the Info.plist file.

The new home is in `git tag`. `script/version` will now fetch the latest git tag on the current branch, strip the `v` prefix, and generate `Sources/MasKit/Package.swift` using the tag as the `Package.Version` constant used by `VersionCommand`.

2021-04-30 19:18 UTC, rgoldberg commented
Will a new version be released once this & #352 are merged?

Some apps are no being upgraded by `mas upgrade` in 1.8.1. I want to investigate & possibly fix these issues, but it doesn't make sense to do so until your recent changes have been merged into `master`, and preferably released, too.

2021-04-30 20:23 UTC, chris-araman commented
@rgoldberg, I hope so. I have some other proposals (https://github.com/mas-cli/mas/pull/346#issuecomment-827123829, https://github.com/mas-cli/mas/issues/344#issuecomment-829374217, https://github.com/mas-cli/mas/issues/309#issuecomment-827966033) in the works, but none of them should prevent this PR and the previous ones from being released.

2021-04-30 22:32 UTC, rgoldberg commented
Cool. Best to release everything that's almost ready ASAP, instead of delaying those things for new PRs.

2021-05-02 18:07 UTC, chris-araman commented
@rgoldberg, you're a member of the mas-cli organization. Are you available to review this PR?

2021-05-02 19:04 UTC, phatblat commented
@rgoldberg @chris-araman FYI the 3 of us are the only active members of the mas-cli org. I would like to get a [release](https://github.com/mas-cli/mas/releases/tag/untagged-42110dadf15c18842d90) out soon and think we're still looking at a patch release (1.8.2) with bug fixes and (many great) project improvements.

One piece that I haven't figured out yet is what to do about the hosting for the bottle files for our custom [homebrew-tap](https://github.com/mas-cli/homebrew-tap) since [Bintray has be sunsetted](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). This shouldn't block the release.

2021-05-02 19:04 UTC, rgoldberg commented
Unfortunately, I know almost nothing about Xcode, Swift, Apple APIs, etc. I'm a JVM developer. the `mas update` / `mas outdated` PR was the first time I coded in Swift or used Xcode. I know nothing about standard Apple project structures, SPMs, Frameworks, etc., so I don't have the requisite knowledge to review this. I'd happily review it, if I were qualified. I can, however, tinker around to investigate the few issues I've run into, and try to fix them, when it's more of straight ahead programming rather than knowing the ins & outs of the whole Apple ecosystem / platform. Sorry. Wish I could be more help.

2021-05-02 19:08 UTC, phatblat commented
No worries, @rgoldberg! Any help is very appreciated! You are welcome to propose changes even if you're not sure if the code is right. @chris-araman and I can help with suggestions. Or, we work out the Swift and lower level stuff with your input on testing and reproducing issues.

2021-05-02 19:11 UTC, chris-araman commented
> One piece that I haven't figured out yet is what to do about the hosting for the bottle files for our custom [homebrew-tap](https://github.com/mas-cli/homebrew-tap) since [Bintray has be sunsetted](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). This shouldn't block the release.

It looks like Homebrew has migrated to GitHub Packages. Perhaps we should too?

2021-05-02 19:24 UTC, phatblat commented
> It [looks like](https://github.com/Homebrew/discussions/discussions/691#discussioncomment-584299) Homebrew has migrated to GitHub Packages. Perhaps we should too?
> 
> I've opened [mas-cli/homebrew-tap#19](https://github.com/mas-cli/homebrew-tap/issues/19) for tracking.

👍🏻 My thoughts exactly 😉

2021-05-02 19:26 UTC, phatblat commented
@chris-araman I'm re-reviewing this PR so we can merge today.

2021-05-02 19:31 UTC, phatblat commented on Sources/MasKit/Formatters/AppListFormatter.swift
> +            let appName = product.appNameOrBundleIdentifier.padding(toLength: maxLength, withPad: " ", startingAt: 0)
Oops! Thanks for fixing this typo.

2021-05-02 19:32 UTC, phatblat commented on Sources/MasKit/Formatters/Utilities.swift
> +        observer(output)
Fancy!

2021-05-02 19:32 UTC, phatblat commented on Sources/MasKit/Models/SoftwareProduct.swift
> +    var appNameOrBundleIdentifier: String {
👍🏻

2021-05-02 19:44 UTC, chris-araman commented on Sources/MasKit/Formatters/Utilities.swift
> +        observer(output)
Or an ugly hack, depending on your point of view. 😉

2021-05-02 19:48 UTC, phatblat commented on script/release
> -# Not currently in use.
👍🏻 I'll document the steps I go through to release. I'd love to have a github action on release which won't need tagging as the GitHub release creates a tag.

2021-05-02 19:59 UTC, chris-araman commented on script/release
> -# Not currently in use.
Sounds good. I was realizing that I don't know the process as I was working on this PR.

2021-05-02 20:40 UTC, phatblat requested changes
Fantastic work! I love seeing deletes since they are removing cruft.

I found one issue with the `version` command that I'd like you to look into.

2021-05-02 20:40 UTC, phatblat commented on Sources/MasKit/Commands/Version.swift
> +        print(Package.Version)
I'm seeing extra characters in the `version` command output.

```
↪ .build/x86_64-apple-macosx/debug/mas version
["1.8.1"]
```

Any ideas where the quotes and brackets are coming from?

2021-05-02 21:43 UTC, chris-araman commented on Sources/MasKit/Commands/Version.swift
> +        print(Package.Version)
🙈 Fixed!

2021-05-03 07:11 UTC, phatblat approved these changes

2021-05-03 07:19 UTC, merged