🤞🏼 Rephrase async code as PromiseKit Promises
mas-cli/mas pull request #362
Opened 2021-05-07 02:33 UTC by chris-araman

RE: https://github.com/mas-cli/mas/pull/346#issuecomment-824562491

Using [Combine](https://developer.apple.com/documentation/combine) would seem to be the future-proof option, as that's the API Apple has produced for asynchronous programming. However, we can't use Apple's Combine yet because it requires macOS 10.15. There are some open source implementations that support older macOS releases.
🔴 [CombineX](https://github.com/cx-org/CombineX) failed `swift build`.
🟡 I made some progress with [OpenCombine](https://github.com/OpenCombine/OpenCombine), but got stuck when I found that it doesn't [yet](https://github.com/OpenCombine/OpenCombine/pull/72) implement [`merge`](https://github.com/OpenCombine/OpenCombine/issues/141).

So, here's the async code rephrased as [PromiseKit](https://github.com/mxcl/PromiseKit) promises.

👍🏼 Pros:
- 81 fewer LOC in `mas` and `MasKit`.
- Arguably improved readability.
- PromiseKit is well documented and seems to have good test coverage.

👎🏼 Cons:
- The default PromiseKit configuration assumes a UI app. `MasKit.initialize` configures PromiseKit for use in a console app, where we regularly wait on the main queue for promises to complete on the global queue. `main.swift` and all test case entry points invoke `MasKit.initialize`.
- It's another dependency to maintain.
- The `mas` executable increases in size by ~824 KiB, or ~53%. This is using the release configuration. I might be able to reduce this with further investigation, but considering we just shed ~13 MiB from `MasKit.framework`, I think it's probably fine.

I'm open to keeping this or dropping it. I'll leave it up to your best judgment, @phatblat.

ℹ️ Commit https://github.com/mas-cli/mas/commit/fb01f5b105a503af445202a93ff0464fd32980cc is here only to maintain existing behavior. With this commit, commands that download (or purchase) multiple apps will continue to attempt all downloads even if an earlier download fails. Without this commit, we'll stop downloading at the first failure. I'm inclined to think the behavior without this commit (failing fast) is what users would expect, but perhaps it's common for one download to fail while others succeed for reasons unrelated to [network failures](https://github.com/mas-cli/mas/issues/344). If you agree, feel free to pop that commit off the stack, or ask me to do so, before merging.

2021-05-07 02:55 UTC, phatblat commented
I want to get the release out before we make this change. Also want to give time to review it properly.

2021-05-09 02:51 UTC, chris-araman commented
Fixes #344 with 38b7373.

With the async logic now described in terms of promises, implementing retry logic was pretty straightforward.

```bash
caraman@mac ~/s/mas (promisekit)> swift run mas install 462062816
==> Downloading Microsoft PowerPoint
Warning: The Internet connection appears to be offline.
Trying again up to 2 more times.
==> Downloading Microsoft PowerPoint
Warning: The Internet connection appears to be offline.
Trying again up to 1 more time.
==> Downloading Microsoft PowerPoint
###################################################--------- 85.0% Installing
```

2021-05-09 03:31 UTC, phatblat requested changes
One idea for the tests

2021-05-09 03:31 UTC, phatblat commented on Tests/MasKitTests/MasQuickSpec.swift
> +        MasKit.initialize()
I've never used it before, but I wonder if Quick's [`beforeSuite`](https://github.com/Quick/Quick/blob/72e9afa98f00c719b16c359d67d95366bad0a460/Documentation/en-us/QuickExamplesAndGroups.md#global-setupteardown-using-beforesuite-and-aftersuite) would eliminate the need to subclass `QuickSpec`.

2021-05-09 04:19 UTC, chris-araman commented on Tests/MasKitTests/MasQuickSpec.swift
> +        MasKit.initialize()
Great idea! Thank you. Works well.

2021-05-12 03:57 UTC, phatblat approved these changes

2021-05-12 03:59 UTC, merged