👷🏻‍♂️ Switch to self-hosted runner
mas-cli/mas pull request #382
Opened 2021-05-13 06:04 UTC by phatblat

Fixes #380

2021-05-13 07:19 UTC, phatblat commented
Got it working tonight but need to set up runner app to start as a service before this will be ready to merge.

2021-05-13 07:27 UTC, chris-araman requested changes

2021-05-13 07:27 UTC, chris-araman commented on script/test
> +swift test 2>&1
I think we can remove the `stderr` redirection as well. It was only there so `xcpretty` could process the test output, which `swift test` prints to `stderr`.

If we're not going to use `xcpretty`, we can remove it from `Gemfile`, then `bundle update` to remove it from `Gemfile.lock`.

2021-05-13 07:28 UTC, chris-araman commented
Nice work! It'll be good to be ahead of the game with this.

2021-05-13 18:55 UTC, phatblat commented on script/test
> +swift test 2>&1
I'll remove the xcpretty dependency. I was surprised that it makes the `swift build` output _more_ verbose whereas it makes the xcodebuild output much more concise.

2021-05-13 18:58 UTC, chris-araman submitted a review, later dismissed

2021-05-13 18:59 UTC, chris-araman commented on script/test
> +swift test 2>&1
Oh, that is interesting.

2021-12-23 23:40 UTC, chris-araman commented on .github/workflows/build-test.yml
> +    # https://github.com/mas-cli/mas/settings/actions/runners
Why does this runner have an `x64` tag?

2021-12-24 20:05 UTC, phatblat commented on .github/workflows/build-test.yml
> +    # https://github.com/mas-cli/mas/settings/actions/runners
Our [runner](https://github.com/mas-cli/mas/settings/actions/runners) has that `x64` tag auto-added by the config step that connects it to GitHub. I can probably override that tag, but I believe it's one of the symptoms showing that the latest release of the runner isn't really running in arm64 mode. The other is the errors Homebfrew spits out when the `bootstrap` script runs:

```text
Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

Version [v2.286.0](https://github.com/actions/runner/releases/tag/v2.286.0) now uses dotnet 6 which supposedly supports M1 natively, but it doesn't seems to work yet. Hope I'm just missing something.

2021-12-24 20:09 UTC, chris-araman commented on .github/workflows/build-test.yml
> +    # https://github.com/mas-cli/mas/settings/actions/runners
Cool. Thanks for looking at all this! I wonder if it's still running on Rosetta?

2021-12-24 20:15 UTC, phatblat commented on .github/workflows/build-test.yml
> +    # https://github.com/mas-cli/mas/settings/actions/runners
I removed the `arch -x86_64` prefix that got this to work under Rosetta.

I wonder if there's a required change on the GitHub side to actually support this since all macOS runners are added with this `x64` architecture.
<img width="358" alt="Screen Shot 2021-12-24 at 1 14 02 PM" src="https://user-images.githubusercontent.com/28851/147371248-aedb424d-bfd3-44ac-983b-e045ff3a4b23.png">

2021-12-24 21:03 UTC, phatblat commented
Getting farther with a [shell command wrapper](https://github.com/mas-cli/mas/pull/382/files#diff-063ca77e012f959eba648db60e6868875fd1e70e5f5ac081193d848f8d61ef32R28) to force scripts to run outside Rosetta.

2021-12-24 21:09 UTC, phatblat commented
The forced architecture for scripts worked to run brew commands in `bootstrap` but now it's failing on the `version` script, perhaps because of `fetch-depth` not being big enough to pick up any tags.

```yml
    - uses: actions/checkout@v2
      with:
        # Fetch tags for script/version
        fetch-depth: 0
```

2021-12-24 21:15 UTC, phatblat commented
I don't think the `fetch-depth` is a problem. Running the `version` script manually on the runner in `actions-runner/_work/mas/mas` works fine and I can see a lot of history in the cloned repo including the `v1.8.6` tag from 4 days and  5 commits ago. Must be some other environment difference, perhaps affecting the `SCRIPT_PATH` variable.

2021-12-24 21:25 UTC, phatblat commented
Not sure why the `version` script failed that one time as the build is working perfectly now!

I want to do a little more cleanup after my experiments, set the runner app to autolaunch on startup and move the mini back into my DMZ vlan before we merge this PR.

2021-12-24 21:29 UTC, phatblat commented
FYI, m1 is running macOS Monterey 12.1 and Xcode 13.2.1 is the default. Homebrew needs to be run as an admin so I want to add codeowners requiring `admin` review of any workflow changes as well as not running actions without approval. There's nothing sensitive on this box but still don't want someone to be able to trash it.

2021-12-25 20:49 UTC, chris-araman commented
> I don't think the `fetch-depth` is a problem.

A `fetch-depth` of `0` is [supposed](https://github.com/actions/checkout#checkout-v2) to fetch all history for all branches and tags.

2021-12-25 20:49 UTC, chris-araman approved these changes

2021-12-26 19:30 UTC, merged